"""Initial migration with workforce prefix

Revision ID: e15a510bb420
Revises: 
Create Date: 2026-01-07 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e15a510bb420'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workforce_employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('designation', sa.String(length=64), nullable=True),
    sa.Column('skills', sa.Text(), nullable=True),
    sa.Column('availability_status', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('workforce_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('client_name', sa.String(length=64), nullable=False),
    sa.Column('required_skills', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workforce_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('allocated_hours', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['workforce_employees.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['workforce_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workforce_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['workforce_employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workforce_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workforce_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_workforce_users_username'), ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workforce_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workforce_users_username'))
        batch_op.drop_index(batch_op.f('ix_workforce_users_email'))

    op.drop_table('workforce_users')
    op.drop_table('workforce_allocations')
    op.drop_table('workforce_projects')
    op.drop_table('workforce_employees')
    # ### end Alembic commands ###
